blank_issues_enabled: false

contact_links:
  - name: BusinessPlus Community PowerShell Module Support
    url: https://github.com/BusinessPlus-Community/PSBusinessPlusERP/discussions
    about: Please ask and answer questions here.
